# Generated by Django 5.0.2 on 2024-03-16 12:41

import ckeditor_uploader.fields
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/')),
                ('user_id', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('clerk', 'Clerk'), ('judge', 'Judge'), ('participant', 'Participant'), ('lawyer', 'Lawyer')], default='observer', max_length=30)),
                ('national_id', models.IntegerField(unique=True)),
                ('county_of_residence', models.CharField(choices=[('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Mombasa', 'Mombasa'), ("Murang'a", "Murang'a"), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita Taveta', 'Taita Taveta'), ('Tana River', 'Tana River'), ('Tharaka Nithi', 'Tharaka Nithi')], default='Nairobi', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer not to say', 'Prefer not to say')], default='prefer not to say', max_length=30)),
                ('tribe', models.CharField(choices=[('Kikuyu', 'Kikuyu'), ('Luhya', 'Luhya'), ('Luo', 'Luo'), ('Kalenjin', 'Kalenjin'), ('Kamba', 'Kamba'), ('Kisii', 'Kisii'), ('Mijikenda', 'Mijikenda'), ('Meru', 'Meru'), ('Turkana', 'Turkana'), ('Maasai', 'Maasai'), ('Embu', 'Embu'), ('Taita', 'Taita'), ('Giriama', 'Giriama'), ('Rendille', 'Rendille'), ('Borana', 'Borana'), ('Samburu', 'Samburu'), ('Pokomo', 'Pokomo'), ('Orma', 'Orma'), ('Elmolo', 'Elmolo'), ('Digo', 'Digo'), ('Swahili', 'Swahili'), ('Taveta', 'Taveta'), ('Kuria', 'Kuria'), ('Mbeere', 'Mbeere'), ('Tharaka', 'Tharaka'), ('Gusii', 'Gusii'), ('Ilchamus', 'Ilchamus'), ('Kalenjin', 'Kalenjin'), ('Kamba', 'Kamba'), ('Kikuyu', 'Kikuyu'), ('Kisii', 'Kisii'), ('Kuria', 'Kuria'), ('Luhya', 'Luhya'), ('Luo', 'Luo'), ('Maasai', 'Maasai'), ('Meru', 'Meru'), ('Mijikenda', 'Mijikenda'), ('Pokomo', 'Pokomo'), ('Rendille', 'Rendille'), ('Samburu', 'Samburu'), ('Somali', 'Somali'), ('Swahili', 'Swahili'), ('Taita', 'Taita'), ('Taveta', 'Taveta'), ('Tharaka', 'Tharaka'), ('Turkana', 'Turkana'), ('Gabra', 'Gabra'), ('Giriama', 'Giriama')], default='Kikuyu', max_length=30)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=30, unique=True)),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('family', 'Family'), ('land', 'Land'), ('commercial', 'Commercial'), ('labour', 'Labour'), ('constitutional', 'Constitutional'), ('environmental', 'Environmental'), ('appeal', 'Appeal'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=30)),
                ('case_status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('concluded', 'Concluded')], default='pending', max_length=30)),
                ('case_name', models.CharField(max_length=255)),
                ('case_description', models.TextField()),
                ('date_filed', models.DateField()),
                ('date_hearing', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('amicus', models.ManyToManyField(blank=True, related_name='amicus', to=settings.AUTH_USER_MODEL)),
                ('clerks', models.ManyToManyField(blank=True, related_name='clerks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('defendants', models.ManyToManyField(blank=True, related_name='defendants', to=settings.AUTH_USER_MODEL)),
                ('judges', models.ManyToManyField(blank=True, related_name='judges', to=settings.AUTH_USER_MODEL)),
                ('lawyers', models.ManyToManyField(blank=True, related_name='lawyers', to=settings.AUTH_USER_MODEL)),
                ('observers', models.ManyToManyField(blank=True, related_name='observers', to=settings.AUTH_USER_MODEL)),
                ('plaintiffs', models.ManyToManyField(blank=True, related_name='plaintiffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseProceeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=30, unique=True)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('evidence', 'Evidence'), ('order', 'Order'), ('report', 'Report'), ('motion', 'Motion'), ('judgement', 'Judgement'), ('opinion', 'Opinion'), ('agreement', 'Agreement'), ('statement', 'Statement'), ('notice', 'Notice'), ('affidavit', 'Affidavit'), ('brief', 'Brief'), ('complaint', 'Complaint'), ('memorandum', 'Memorandum'), ('declaration', 'Declaration'), ('deposition', 'Deposition'), ('pleading', 'Pleading'), ('petition', 'Petition'), ('reply', 'Reply'), ('warrant', 'Warrant'), ('will', 'Will'), ('subpoena', 'Subpoena'), ('transcript', 'Transcript'), ('verdict', 'Verdict'), ('appeal', 'Appeal'), ('sentence', 'Sentence'), ('ruling', 'Ruling'), ('decree', 'Decree'), ('directive', 'Directive'), ('mandate', 'Mandate'), ('injunction', 'Injunction'), ('citation', 'Citation'), ('summons', 'Summons'), ('writ', 'Writ')], max_length=30)),
                ('filed_as', models.CharField(choices=[('admin', 'Admin'), ('clerk', 'Clerk'), ('judge', 'Judge'), ('participant', 'Participant'), ('lawyer', 'Lawyer')], max_length=255)),
                ('filed_on', models.DateTimeField(auto_now_add=True)),
                ('confidentiality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=30)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court_proceedings_management_application.case')),
                ('editors', models.ManyToManyField(blank=True, related_name='editors', to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('court_id', models.CharField(max_length=30, unique=True)),
                ('court_logo', models.ImageField(blank=True, default='court_logos/default.png', null=True, upload_to='court_logos/')),
                ('court_email', models.EmailField(max_length=254)),
                ('court_phone', models.CharField(blank=True, max_length=15)),
                ('court_address', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Mombasa', 'Mombasa'), ("Murang'a", "Murang'a"), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita Taveta', 'Taita Taveta'), ('Tana River', 'Tana River'), ('Tharaka Nithi', 'Tharaka Nithi')], max_length=255)),
                ('court_type', models.CharField(choices=[('high court', 'High Court'), ('magistrate court', 'Magistrate Court'), ('environment court', 'Environment and Land Court'), ('labour court', 'Employment and Labour Court'), ('anti-corruption court', 'Anti-Corruption Court'), ('children court', "Children's Court"), ('maritime court', 'Maritime Court'), ('military court', 'Military Court'), ('tax court', 'Tax Court'), ('appeal court', 'Court of Appeal'), ('supreme court', 'Supreme Court')], max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court_proceedings_management_application.court'),
        ),
        migrations.AddField(
            model_name='user',
            name='courts',
            field=models.ManyToManyField(blank=True, related_name='users', to='court_proceedings_management_application.court'),
        ),
    ]
