# Generated by Django 5.0.2 on 2024-03-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_proceedings_management_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='court_logo',
            field=models.ImageField(blank=True, default='../static/images/default_court.png', null=True, upload_to='court_logos/'),
        ),
    ]
