# Generated by Django 5.0.2 on 2024-03-18 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_proceedings_management_application', '0006_remove_relief_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='relief',
            name='case_proceeding',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='court_proceedings_management_application.caseproceeding'),
        ),
    ]
