# Generated by Django 5.0.2 on 2024-03-18 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_proceedings_management_application', '0008_alter_relief_case_proceeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=30, unique=True)),
                ('invoice_type', models.CharField(choices=[('court fees', 'Court Fees'), ('legal fees', 'Legal Fees'), ('filing fees', 'Filing Fees'), ('service fees', 'Service Fees'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=30)),
                ('invoice_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('invoice_amount', models.IntegerField()),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('invoice_due_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('case_proceeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court_proceedings_management_application.caseproceeding')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relieved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court_proceedings_management_application.relief')),
            ],
        ),
    ]
