# Generated by Django 5.0.2 on 2024-03-19 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_proceedings_management_application', '0009_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='participant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
