# Generated by Django 5.0.2 on 2024-04-02 22:09

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_proceedings_management_application', '0011_alter_invoice_relieved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('checkout_request_id', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Complete'), (2, 'Failed'), (3, 'Cancelled'), (4, 'Refunded')], default=1, max_length=15)),
                ('receipt_no', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='court_proceedings_management_application.invoice')),
                ('paid_for', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_recepient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
