# Generated by Django 5.0.2 on 2024-05-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_proceedings_management_application', '0013_transaction_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
